### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by senger1985** [soef/ioBroker.alexa#11]
If I install the adapter, I get an error:
instance system.adapter.alexa.0 terminated with code 1 ()
Pi 3 with ioBroker.admin 3.2.0

**Comment by soef** [comment]
Hello, I made a fresh install of ioBroker on a Raspberry 3 and install the Adapter by
npm install iobroker.alexa
After entering the user / email and password everything worked.
I can not reproduce your problem. Do you have more information?

**Comment by senger1985** [comment]
Sorry, it was my mistake.
The path for the cooki was wrong in the script
