### ISSUE TITLE
Wunsch: Button um alle Items von Liste löschen

### ISSUE THREAD

**Issue by Azathoth88** [soef/ioBroker.alexa#27]
Bisher kann jedes Item lediglich einzeln per Button gelöscht werden. Es wäre schön, wenn es hierzu ein Pendant geben würde, welches alle Items einer Liste löschen kann.

Als Beispiel:
Ich habe eine Einkaufsliste; gehe Einkaufen und möchte dann alle Items von der Liste entfernen.

**Comment by oberstel** [comment]
Du könntest einfach mal auf den aktuellen Adapter [Alexa2](https://github.com/Apollon77/ioBroker.alexa2) wechseln.
Dieser hier wird nicht weiterentwickelt.

**Comment by Azathoth88** [comment]
Hast du mal auf das Datum geschaut? Das Feature-Request ist von 2019... Ich bin schon längst gewechselt.

**Comment by oberstel** [comment]
> Hast du mal auf das Datum geschaut? Das Feature-Request ist von 2019... Ich bin schon längst gewechselt.

Tut mir leid, dass ich Dir helfen wollte.

**Comment by Azathoth88** [comment]
Nimm es nicht persönlich. Ich bin Leichenschänderei sonst nur bei Foren gewöhnt. Trotzdem Danke für deine Hilfe.
