### ISSUE TITLE
Mask of E-Mail-Address

### ISSUE THREAD

**Issue by gBonfire** [soef/ioBroker.alexa#7]
Hello,

i can*t verify this, but it seems to be a Problem with "-" in E-Mailadress.
Because when i use Email and PW, the Error-Log shows "alexa.0 | 2018-01-28 14:33:33.637 | error | no csrf found. Check configuration of email/password or cookie-- | -- | -- | --"

When i added the cookie manuell, all workes fine.

My E-Mail have an "-", eg. xxxxx@t-online.de

Thank you !

**Comment by Arnulf22** [comment]
In my email address is  an "-" too. But it is working

**Comment by gBonfire** [comment]
Ok. So this seem a local Problem on my side. I close this issue, because the description seems wrong. I hope i find the correct root cause.
Thanks and bye. 
PS:Meanwhile i add the cookie via Script. This workaround work for me
