### ISSUE TITLE
windows iobroker adapter not start

### ISSUE THREAD

**Issue by elzershark** [soef/ioBroker.alexa#8]
ioBroker.admin 3.1.12
Cloud 2.4.5
Node 4.5.0
npm 2.15.9

in raspberry iobroker is all ok
in windows iobroker not start the Adapter.

p.s.
i coppy the Cookie from raspy to windows.
that too is not possible

`

host.DESKTOP-1T3IK9T | 2018-02-13 23:18:39.692 | error | instance system.adapter.alexa.0 terminated with code 1 ()
-- | -- | -- | --
host.DESKTOP-1T3IK9T | 2018-02-13 23:18:39.204 | info | instance system.adapter.alexa.0 started with pid 6632
host.DESKTOP-1T3IK9T | 2018-02-13 23:18:09.164 | info | Restart adapter system.adapter.alexa.0 because enabled
host.DESKTOP-1T3IK9T | 2018-02-13 23:18:09.164 | error | instance system.adapter.alexa.0 terminated with code 1 ()
host.DESKTOP-1T3IK9T | 2018-02-13 23:18:08.644 | info | instance system.adapter.alexa.0 started with pid 5376
host.DESKTOP-1T3IK9T | 2018-02-13 23:17:38.605 | info | Restart adapter system.adapter.alexa.0 because enabled
host.DESKTOP-1T3IK9T | 2018-02-13 23:17:38.605 | error | instance system.adapter.alexa.0 terminated with code 1 ()
host.DESKTOP-1T3IK9T | 2018-02-13 23:17:38.096 | info | instance system.adapter.alexa.0 started with pid 6048
host.DESKTOP-1T3IK9T | 2018-02-13 23:17:08.044 | info | Restart adapter system.adapter.alexa.0 because enabled
host.DESKTOP-1T3IK9T | 2018-02-13 23:17:08.044 | error | instance system.adapter.alexa.0 terminated with code 1 ()
host.DESKTOP-1T3IK9T | 2018-02-13 23:17:07.552 | info | instance system.adapter.alexa.0 started with pid 7120
host.DESKTOP-1T3IK9T | 2018-02-13 23:16:37.496 | info | Restart adapter system.adapter.alexa.0 because enabled
host.DESKTOP-1T3IK9T | 2018-02-13 23:16:37.496 | error | instance system.adapter.alexa.0 terminated with code 1 ()
host.DESKTOP-1T3IK9T | 2018-02-13 23:16:37.000 | info | instance system.adapter.alexa.0 started with pid 1436
host.DESKTOP-1T3IK9T | 2018-02-13 23:16:06.963 | info | Restart adapter system.adapter.alexa.0 because enabled
host.DESKTOP-1T3IK9T | 2018-02-13 23:16:06.963 | error | instance system.adapter.alexa.0 terminated with code 1 ()
host.DESKTOP-1T3IK9T | 2018-02-13 23:16:06.462 | info | instance system.adapter.alexa.0 started with pid 3296
host.DESKTOP-1T3IK9T | 2018-02-13 23:15:36.422 | info | Restart adapter system.adapter.alexa.0 because enabled
host.DESKTOP-1T3IK9T | 2018-02-13 23:15:36.422 | error | instance system.adapter.alexa.0 terminated with code 1 ()
host.DESKTOP-1T3IK9T | 2018-02-13 23:15:35.921 | info | instance system.adapter.alexa.0 started with pid 3536
host.DESKTOP-1T3IK9T | 2018-02-13 23:15:35.872 | info | object change system.adapter.alexa.0
host.DESKTOP-1T3IK9T | 2018-02-13 23:15:21.580 | info | Restart adapter system.adapter.alexa.0 because enabled
host.DESKTOP-1T3IK9T | 2018-02-13 23:15:21.580 | error | instance system.adapter.alexa.0 terminated with code 1 ()
host.DESKTOP-1T3IK9T | 2018-02-13 23:15:21.053 | info | instance system.adapter.alexa.0 started with pid 4612

`

**Comment by soef** [comment]
Hallo, normaly the Adapter runs also under Windows. I'm using it on Windows 10. Can you Switch the Log-State to debug to get mor Information?

**Comment by elzershark** [comment]
This is the same ;)

**Comment by elzershark** [comment]
Debug can not show anything because the adapter is not running;)
Debug kann nichts anzeigen da der Adapter nicht läuft ;)

**Comment by elzershark** [comment]
What do you have for
ioBroker.admin 
Cloud 
Node 
npm 
web

Version in Windows 10?
this problem is of windows 10 (64bit)

**Comment by soef** [comment]
Hi, I have different ioBroker environments. Most under Windows 10 (64bit). The adapter runs everywhere. If there are no debug outputs in the log, the adapter code will not be executed. Try to find differences in your ioBroker installation on the Raspberry and Windows 10.

If you are german (I am), we can write in german.

**Comment by elzershark** [comment]
ok. Bin auch Deutsch..
Weiß nicht ob das so geht. ich hab hier ein log. hab mal die alexa.js im cmd selber ausgeführt.
das wird angezeigt:

```
C:\ioBroker\node_modules\iobroker.alexa\node_modules\alexa-remote\alexa-remote.js:159
    this.httpsGet = function (path, callback, flags = {}) {
                                                    ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\ioBroker\node_modules\iobroker.alexa\alexa.js:5:13)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

C:\ioBroker\node_modules\iobroker.alexa>node alexa.js --force --logs
C:\ioBroker\node_modules\iobroker.alexa\node_modules\alexa-remote\alexa-remote.js:159
    this.httpsGet = function (path, callback, flags = {}) {
                                                    ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\ioBroker\node_modules\iobroker.alexa\alexa.js:5:13)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

C:\ioBroker\node_modules\iobroker.alexa>
```

**Comment by elzershark** [comment]
Hier mit Cookie:

```
C:\ioBroker\node_modules\iobroker.alexa>node alexa.js --force --logs
C:\ioBroker\node_modules\iobroker.alexa\node_modules\alexa-remote\alexa-remote.js:159
    this.httpsGet = function (path, callback, flags = {}) {
                                                    ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\ioBroker\node_modules\iobroker.alexa\alexa.js:5:13)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

C:\ioBroker\node_modules\iobroker.alexa>
```

**Comment by soef** [comment]
Super, das du den Adapter einmal in einem cmd Fenster ausgeführt hast. Bei den Ausgaben sieht man das Problem schon. Die eingesetzte Node-Version ist zu gering. Sie versteht noch keine Default-Parameter beim Aufruf einer Funktion. Die Node.js Version sollte >= 6.xx sein. Dann müsste es funktionieren.

**Comment by elzershark** [comment]
Super. Hab erstmal Version 8 installiert. Funzt. Danke dir.
